### ISSUE TITLE
JSX curly spacing

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/eslint-config#14]
Airbnb are now discouraging JSX curly spacing, preferring:

``` html
<MyComponent prop={hello} />
```

over

``` html
<MyComponent prop={ hello } />
```

See https://github.com/airbnb/javascript/issues/693.

How do we feel about this?

**Comment by sindrenm** [comment]
+1 for the padding spaces!

**Comment by jgorset** [comment]
I dig.
