### ISSUE TITLE
Comma dangling

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/eslint-config#2]
The [comma-dangle rule](http://eslint.org/docs/rules/comma-dangle.html) controls whether dangling commas in object/array literals are enforced or disallowed.

The [inherited configuration from Airbnb](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/base/index.js#L53) requires dangling commas when dealing with multi-line literals:

``` javascript
const people = [
  'tim',
  'sindre',
  'bear',
];
```

Is this something we want to override in our configuration?

**Comment by sindrenm** [comment]
While I agree that the dangling comma looks kinda ugly, it's kinda practical. For once, it makes adding new things to the arrays or objects or whatever a single-line diff, whereas you would have to change _two_ lines if you weren't using the dangling comma:

``` diff
diff --git a/with.js b/with.js
index c85e97f..b898830 100644
--- a/with.js
+++ b/with.js
@@ -1,4 +1,5 @@
 const bodybuilders = [
   'Rich Piana',
   'Arnold Schwarzenegger',
+  'Jay Cutler',
 ];
diff --git a/without.js b/without.js
index c8454a0..b898830 100644
--- a/without.js
+++ b/without.js
@@ -1,4 +1,5 @@
 const bodybuilders = [
   'Rich Piana',
-  'Arnold Schwarzenegger'
+  'Arnold Schwarzenegger',
+  'Jay Cutler'
 ];
```

Also, with dangling commas, moving stuff around inside the array or object (e.g. for sorting alphabetically or whatever) doesn't require anything else than moving stuff around, whereas without it you would need to make sure that you remove the comma from the one that ends up last and add a comma to the one that was last but is no longer last. In this example, simply moving stuff around without chaning any lines would result in a syntax error in _without.js_, but be perfectly valid in _with.js_:

``` diff
diff --git a/with.js b/with.js
index b898830..2f8cfbc 100644
--- a/with.js
+++ b/with.js
@@ -1,5 +1,5 @@
 const bodybuilders = [
-  'Rich Piana',
   'Arnold Schwarzenegger',
   'Jay Cutler',
+  'Rich Piana',
 ];
diff --git a/without.js b/without.js
index 6bdb514..c262253 100644
--- a/without.js
+++ b/without.js
@@ -1,5 +1,5 @@
 const bodybuilders = [
-  'Rich Piana',
   'Arnold Schwarzenegger',
   'Jay Cutler'
+  'Rich Piana',
 ];
```

**Comment by timkurvers** [comment]
I'm leaning more and more towards keeping the default of enforcing dangling commas :+1:

Even more so after reading airbnb/javascript#323:

> Today’s transpilers like babel remove the last comma anyway

**Comment by JozoSalt** [comment]
Makes sense for multi-line, but kinda don't like it on single line :)
When do a single line become a multi-line ( maybe a stupid question ) ?

**Comment by timkurvers** [comment]
It wouldn't be required for single line literals I don't think.

**Comment by sindrenm** [comment]
> When do a single line become a multi-line ( maybe a stupid question ) ?

I think this is an excelent question, and I have no idea what the answer is.

**Comment by timkurvers** [comment]
Good question. Line length is one factor, the other could be grouping of properties:

``` javascript
const person = {
  firstName: 'Tim',
  lastName: 'Kurvers',

  friends: [{ name: 'Bob' }]
};
```

**Comment by timkurvers** [comment]
I'm leaning towards enforcing dangling commas, which is the current default. :+1:

**Comment by jgorset** [comment]
Sure, I'd be on board with that, too.

**Comment by sindrenm** [comment]
Then we can just close this, right? Since it's already in our guidelines through Airbnb.

**Comment by timkurvers** [comment]
Yeapz! :+1:
